article/urls.py
from django.conf.urls import url

from article import views

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='landing_page'),

    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>[-\w]+)/$',
        views.ArticleDetail.as_view(),
        name='article-detail'),

    url(r'^(?P<year>[0-9]{4})/$',
        views.ArticleYearList.as_view(),
        name='article_year_list'),

    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/$',
        views.ArticleMonthList.as_view(),
        name='article_month_list'),

    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$',
        views.ArticleDayList.as_view(),
        name='article_day_list'),

    url(r'^article/new/$', views.NewArticleView.as_view(),
        name='article_new'),

    url('^article/update/(?P<pk>[\w-]+)/$', views.UpdateArticleView.as_view(),
        name='update_article'),

    url(r'^tag/(?P<pk>[\w-]+)/$', views.TagArticleListView.as_view(),
        name='tag_article_list'),

    url(r'^tag/$', views.TagListView.as_view(), name='tag_list'),

    url(r'^all/$', views.AllArticlesView.as_view(), name='all_articles')

    ]

author/urls.py
from django.conf.urls import url

from author import views

app_name = 'author'

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signout/$', views.SignOutView.as_view(), name='signout'),
    url(r'profile/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'(?P<pk>[\w-]+)/edit/$', views.ProfileEditView.as_view(),
        name='edit_profile')
]

theNews/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^author/', include('author.urls')),
    url(r'^', include('article.urls')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

import datetime

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255,
                             unique_for_date='pub_date')
    slug = models.CharField(max_length=255,
                            blank=True, null=True)
    body = models.TextField()
    pub_date = models.DateField(default=datetime.date.today)
    updated_date = models.DateField(default=datetime.date.today)
    tags = models.ManyToManyField(Tag)
    promoted = models.BooleanField(default=False)
    author = models.ForeignKey(User,
                               null=True,
                               blank=True,
                               default=None,
                               on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'slug': self.slug,
                                                 'year': self.pub_date.strftime("%Y"),
                                                 'month': self.pub_date.strftime("%b"),
                                                 'day': self.pub_date.strftime("%d")}
                       )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']

author/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    pic = models.ImageField(upload_to='user_pics/')

article/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, SelectMultiple, CheckboxInput
from django.forms import TextInput, Textarea

from tinymce.widgets import TinyMCE

from .models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'body', 'promoted', 'tags']

        widgets = {
            'title': TextInput(attrs={'class': 'form-control input-sm'}),
            'body': TinyMCE(attrs={'cols': 80, 'rows': 30, 'class': 'form-control'}),
            'promoted': CheckboxInput(attrs={'class': 'form-checkbox'}),
            'tags': SelectMultiple(attrs={'class': 'form-control'})
        }

article/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from django.views.generic.dates import DateDetailView, YearArchiveView, DayArchiveView, MonthArchiveView

from .models import Article, Tag
from .forms import ArticleForm

# Create your views here.
class HomePageView(TemplateView):
    template_name= "article/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['promoted'] = Article.objects.filter(promoted=True)
        context['latest_articles'] = Article.objects.all()[:5]
        return context

class AllArticlesView(ListView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    make_object_list = True
    template_name = "article/ArticleList.html"
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(AllArticlesView, self).get_context_data(**kwargs)
        context['title'] = "All our articles"
        return context

class ArticleDetail(DateDetailView):
    model=Article
    date_field="pub_date"
    template_name= "article/ArticleDetail.html"


class ArticleYearList(YearArchiveView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    make_object_list = True
    template_name= "article/ArticleList.html"
    paginate_by=20

    def get_context_data(self, **kwargs):
        context = super(ArticleYearList, self).get_context_data(**kwargs)
        context['title'] = "Articles for " + self.kwargs['year']
        return context


class ArticleMonthList(MonthArchiveView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    make_object_list = True
    template_name= "article/ArticleList.html"
    paginate_by=20

    def get_context_data(self, **kwargs):
        context = super(ArticleMonthList, self).get_context_data(**kwargs)
        context['title'] = "Articles for {}, {}".format(self.kwargs['month'],
                                                        self.kwargs['year'])
        return context


class ArticleDayList(DayArchiveView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    make_object_list = True
    template_name= "article/ArticleList.html"
    paginate_by=20

    def get_context_data(self, **kwargs):
        context = super(ArticleDayList, self).get_context_data(**kwargs)
        context['title'] = "Articles for {} {}, {}".format(self.kwargs['day'],
                                                           self.kwargs['month'],
                                                           self.kwargs['year'])
        return context


class NewArticleView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "article/EditArticle.html"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        return super(NewArticleView, self).form_valid(form)


class UpdateArticleView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "article/EditArticle.html"


class TagArticleListView(ListView):
    model = Article
    make_object_list = True
    template_name = "article/ArticleList.html"

    def get_queryset(self):
        queryset = Article.objects.filter(tags__in=self.kwargs['pk'])
        return queryset

class TagListView(ListView):
    model = Tag
    make_object_list = True
    queryset = Tag.objects.all()
    template_name = "article/TagList.html"

article/templates/article/ArticleDetail.html
{%  extends 'base.html' %}

{% block content %}

    <h1>{{ object.title | title }}</h1>
    <div class="by-line">
        <img src="{{ object.author.profile_set.all.0.pic.url }}"
                 class="img-circle" height="50px">

        {% if object.author.first_name %}
            <a href="{% url 'author:profile' object.author.pk %}">
                By: {{ object.author.first_name | title }} {{ object.author.last_name | title }}
            </a>
        {% endif %}
         - {{ object.pub_date }}

        {% if user == article.author %}
            <a href="{% url 'update_article' article.pk %}" class='btn btn-xs btn-info'>
                edit
            </a>
        {% endif %}
    </div>
    <hr>

    <div class="">{{ object.body | safe }}</div>

    <nav>
        {% for tag in object.tags.all %}
            <a href="{% url 'tag_article_list' tag.pk %}">{{ tag.name }}</a>
            <span class="spacer">|</span>
        {%  endfor %}
    </nav>

    {% include "article/commentbox.html" %}

{% endblock %}

article/templates/article/ArticleList.html
{%  extends 'base.html' %}

{% block content %}
    <h2>{{ title | title }}</h2>

    {% if is_paginated %}
        <div class="text-center">
            <ul class="pagination">
            {% if page_obj.has_previous %}
                <li>
                    <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
                </li>
            {% endif %}
                <li class="">
                    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
            {% if page_obj.has_next %}
                <li>
                    <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                </li>
            {% endif %}
            </ul>
        </div>

    {% endif %}

    <table class="table table-condensed table-bordered table-striped">
        {% for article in object_list %}
            <tr>
                <td>
                    <a href="{{ article.get_absolute_url }}">
                        {{ article.title | title}}
                    </a>
                </td>
                <td>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'tag_article_list' tag.pk %}">{{ tag.name }}</a>,
                    {% endfor %}
                </td>
            <td>{{ article.pub_date }}</td>
            </tr>
        {% endfor %}
    </table>


{%  endblock %}

article/templates/article/EditArticle.html
{%  extends 'base.html' %}
{%  load staticfiles %}

{% block content %}

    <form action="#" method="post" name="newArticle" novalidate>
        {%  csrf_token %}
        {{ form }}
        <br>
        <button class="btn btn-info">Submit</button>
    </form>

    <script type="text/javascript"
            src="{% static "tinymce/js/tinymce/tinymce.min.js" %}"></script>
    <script>
    tinyMCE.init({
        mode: "textareas",
        theme: "modern",
        plugins: "directionality,paste,searchreplace,codesample,hr,media,image,wordcount,link,advlist",
        language: "{{ language }}",
        directionality: "{{ directionality }}",
        spellchecker_languages : "{{ spellchecker_languages }}",
        spellchecker_rpc_url : "{{ spellchecker_rpc_url }}",
        codesample_languages: [
            {text: 'HTML/XML', value: 'markup'},
            {text: 'JavaScript', value: 'javascript'},
            {text: 'CSS', value: 'css'},
            {text: 'PHP', value: 'php'},
            {text: 'Ruby', value: 'ruby'},
            {text: 'Python', value: 'python'},
            {text: 'Java', value: 'java'},
            {text: 'C', value: 'c'},
            {text: 'C#', value: 'csharp'},
            {text: 'C++', value: 'cpp'}
        ],
        toolbar: "codesample",
});
    </script>


{%  endblock %}

article/templates/article/TagList.html
{% extends 'base.html' %}

{%  block content %}
    <h2>Category Tags</h2>
    <table class="table table-condensed table-bordered table-striped">
        <thread>
            <tr>
                <th>
                    Tag
                </th>
                <th>
                    Description
                </th>
                <th>#</th>
            </tr>
        </thread>
        {% for tag in object_list %}
            <tr>
                <td>
                    <a href="{% url 'tag_article_list' tag.pk %}">{{ tag | upper}}</a>
                </td>
                <td>
                    {{ tag.description }}
                </td>
                <td> {{ tag.article_set.all.count }}</td>
            </tr></li>
        {%  endfor %}
    </table>
{% endblock %}

article/templates/article/commentbox.html
<br>
Code for a social commenting platform goes here  i.e. Disqus.

article/templates/article/home.html
{%  extends 'base.html' %}

{%  block content %}
    <h2>Latest News</h2>
    <ul>
        {% for article in latest_articles %}
            <li>
                <a href="{{ article.get_absolute_url }}">
                    {{ article.pub_date }} - {{ article.title | title }}
                </a>
            </li>
        {%  endfor %}
    </ul>
    
    {% for promote in promoted %}
        <hr>
        <h3><a href="{{ promote.get_absolute_url }}">
            {{ promote.title | title }}
        </a></h3>
        <div class="by-line">
         {{ promote.pub_date }}
        {% if promote.author.first_name %}
            - By: {{ promote.author.first_name | title }} {{ promote.author.last_name | title }}
        {% endif %}
        {% if user == promote.author %}
            <a href="{% url 'update_article' promote.pk %}" class='btn btn-xs btn-info'>
                edit
            </a>
        {% endif %}
    </div>
        <br>
        {{ promote.body | safe }}
    {% endfor %}


{%  endblock %}