author/urls.py
from django.conf.urls import url

from author import views

app_name = 'author'

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signout/$', views.SignOutView.as_view(), name='signout'),
    url(r'profile/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'(?P<pk>[\w-]+)/edit/$', views.ProfileEditView.as_view(),
        name='edit_profile')
]

theNews/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^author/', include('author.urls')),
    url(r'^', include('article.urls')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0">
        <title>theNews</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="page-header">
                <h1>The News <br><small>Stuff that matters, and some nonsense too.</small>
                </h1>
            </div>
            <nav>
                <a href="/"><span class="glyphicon glyphicon-home"></span></a>
                <span class="spacer">|</span>
                <a href="{% url 'tag_list' %}">Categories</a>
                <span class="spacer">|</span>
                <a href="{% url 'all_articles' %}">All Articles</a>

                {% if not user.is_authenticated %}
                    <span class="spacer">|</span>
                    <a href="{% url 'author:signin' %}">Sign In</a>
                {% else %}
                    <span class="spacer">|</span>
                    <a href="{% url 'article_new' %}">Post</a>
                    <span class="spacer">|</span>
                    <a href="{% url 'author:signout' %}">Sign Out</a>
                {%  endif  %}
            </nav>

            <div class="content">
                {%  block content %} {%  endblock %}
            </div>

            <hr>
            <footer>
                <div class="block"> bottom 1</div>
                <div class="block"> bottom 2</div>
                <div class="block"> bottom 3</div>
            </footer>

        </div>
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"
                integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous"></script>
    </body>

    </html>