author/urls.py
from django.conf.urls import url

from author import views

app_name = 'author'

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signout/$', views.SignOutView.as_view(), name='signout'),
    url(r'profile/(?P<pk>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'(?P<pk>[\w-]+)/edit/$', views.ProfileEditView.as_view(),
        name='edit_profile')
]

theNews/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^author/', include('author.urls')),
    url(r'^', include('article.urls')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

import datetime

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255,
                             unique_for_date='pub_date')
    slug = models.CharField(max_length=255,
                            blank=True, null=True)
    body = models.TextField()
    pub_date = models.DateField(default=datetime.date.today)
    updated_date = models.DateField(default=datetime.date.today)
    tags = models.ManyToManyField(Tag)
    promoted = models.BooleanField(default=False)
    author = models.ForeignKey(User,
                               null=True,
                               blank=True,
                               default=None,
                               on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'slug': self.slug,
                                                 'year': self.pub_date.strftime("%Y"),
                                                 'month': self.pub_date.strftime("%b"),
                                                 'day': self.pub_date.strftime("%d")}
                       )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']

author/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    pic = models.ImageField(upload_to='user_pics/')

author/forms.py
from django import forms

from author.models import Profile


class SigninForm(forms.Form):
        username = forms.CharField(label="Username",
                                   max_length=30,
                                   widget=forms.TextInput(attrs={'class': "form-control input-sm"}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control input-sm'}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'pic']

author/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from author.models import Profile
from .forms import SigninForm, ProfileForm


class SigninView(FormView):
    form_class = SigninForm
    success_url = reverse_lazy('landing_page')
    template_name = 'author/signin.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(SigninView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class SignOutView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self):
        logout(self.request)
        return reverse_lazy('landing_page')


class ProfileView(TemplateView):
    template_name = "author/profile.html"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['author'] = User.objects.get(pk=self.kwargs['pk'])
        return context


class ProfileEditView(UpdateView):
    model = Profile
    form_class = ProfileForm
    success_url = reverse_lazy('landing_page')
    template_name = "author/profileEdit.html"

    def dispatch(self, request, *args, **kwargs):
        profile = Profile.objects.get(pk=kwargs['pk'])
        if request.user != profile.user:
            raise PermissionDenied
        else:
            return super(ProfileEditView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProfileEditView, self).get_context_data(**kwargs)
        context['profile'] = Profile.objects.get(pk=self.kwargs['pk'])
        return context

author/templates/author/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ author.first_name }} {{ author.last_name }}</h2>
    {%  if user == author %}
        <a href="{% url 'author:edit_profile' author.profile_set.all.0.pk %}" class="btn btn-xs btn-info">
            edit
        </a>
    {% endif %}
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object img-rounded"
               src="{{ author.profile_set.all.0.pic.url }}"
               alt="{{ author.first_name }} {{ author.last_name }}">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">Bio</h4>
        {{ author.profile_set.all.0.bio | safe }}
      </div>
    </div>
    <h3>Latest Articles</h3>
    <table class="table table-bordered table-condensed table-striped" >
        {% for article in author.article_set.all|slice:"10" %}
            <tr>
                <td>
                    <a href="{{ article.get_absolute_url }}">
                        {{ article.title | title}}
                    </a>
                </td>
                <td>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'tag_article_list' tag.pk %}">{{ tag.name }}</a>,
                    {% endfor %}
                </td>
            <td>{{ article.pub_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

author/templates/author/profileEdit.html
{%  extends 'base.html' %}

{% block content %}
    <h2>{{ profile.user.first_name }} {{ profile.user.last_name }}</h2>
    <form action="#" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
        <button>submit</button>
    </form>

{% endblock %}

author/templates/author/signin.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-sm-6">
        <h2>Author Sign In</h2>
        <form action="{% url 'author:signin' %}" method="post">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
             <button class="btn btn-info">Sign in</button>
        </form>
    </div>
{%  endblock %}